import React, { FC, useEffect, useState } from 'react';
import { Html, Head, Main, NextScript } from 'next/document';
import { getItems } from '@/api/getItems';
import { getProducts } from '@/redux/products/productsOperations';
import { useAppDispatch, useAppSelector } from '@/redux/hooks';

const Document: FC = () => {
  // const dispatch = useAppDispatch();
  // useEffect(() => {
  //   dispatch(getProducts);
  // }, [dispatch]);
  return (
    <Html lang="uk">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@600;700&family=Inter&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
