import React from 'react';
import Heading from '@/components/Heading/Heading';
import { Container } from '@/components/Container/Container';
import { Section } from '@/components/Section/Section';
import Head from 'next/head';

const History: React.FC = () => {
  return (
    <>
      <Head>
        <title>Pizza - history</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Container>
          <div>
            <Heading>Історія замовлень</Heading>
          </div>
        </Container>
      </Section>
    </>
  );
};

export default History;
