import React from 'react';
import Head from 'next/head';
import Heading from '@/components/Heading/Heading';
import { Container } from '@/components/Container/Container';
import { Section } from '@/components/Section/Section';

export const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Pizza - news</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Container>
          <Heading>Новинки</Heading>
        </Container>
      </Section>
    </>
  );
};

export default Home;
