import Head from 'next/head';
import Heading from '@/components/heading/Heading';
import { Container } from '@/components/container/Container';
import { Section } from '@/components/section/Section';

export const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Container>
          <Heading heading={'Новинки'} />
        </Container>
      </Section>
    </>
  );
};

export default Home;
